openapi: 3.0.2
info:
  title: Geospatial Map Provider Automated Testing Interface
  version: 0.1.0
  license:
    name: Apache License v2.0
    url: https://github.com/interuss/automated_testing_interfaces/blob/main/LICENSE.md
  description: >-
    This interface is implemented by a USS to provide uss_qualifier (and perhaps other similar clients) with the
    capability to pretend to be a user interacting with the USS's geospatial map representation for the purpose of
    evaluating potential flight plans.
    
    This interface is used by InterUSS's geospatial feature comprehension tests, so every USS wishing to be tested by
    those tests must implement this interface.
    
    The automated testing suite may call this interface to first load test data into the USS system under test, and then
    will perform virtual queries on the USS's geospatial map to evaluate its processing and interpretation of the
    relevant geospatial data.

servers:
  - url: https://uss.example.com/geospatial_map

components:
  securitySchemes:
    TestAuthority:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            interuss.geospatial_map.direct_automated_test: |-
              Client may determine the test-readiness of the USS and instruct the USS to load geospatial data from
              specified data sources (acting as a test director).
            interuss.geospatial_map.query: |-
              Client may read information from the USS's geospatial map (acting as a user of the USS's geospatial map).
      description: |-
        Authorization from, or on behalf of, an authorization authority, augmenting standard Geo-Awareness authorization for the purpose of automated testing.

  schemas:
    UUIDv4Format:
      description: >-
        String whose format matches a version-4 UUID according to RFC 4122.
      maxLength: 36
      minLength: 36
      type: string
      format: uuid
      pattern: >-
        ^[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-4[0-9a-fA-F]{3}\\-[8-b][0-9a-fA-F]{3}\\-[0-9a-fA-F]{12}$
      example: 03e5572a-f733-49af-bc14-8a18bd53ee39

    StatusResponse:
      type: object
      required:
        - status
      properties:
        status:
          description: >-
            The status of the USS automated testing interface.

            - `Starting`: the USS is starting and the automated test driver should wait before sending requests.

            - `Ready`: the USS is ready to receive test requests.
          type: string
          enum: [Starting, Ready]
          example: Ready
        version:
          description: |-
            Arbitrary string representing the version of the USS system to be tested.
          type: string
          example: v0.0.1-445ad3

    CreateGeospatialDataSourceRequest:
      type: object
      properties:
        https_source:
          $ref: '#/components/schemas/GeospatialHttpsSource'

    GeospatialHttpsSource:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: url
          description: The URL at which the Geospatial data shall be downloaded from.
          example: https://caa.example.com/geozones.json
        format:
          type: string
          description: The format of the response expected from the source.
          enum: [ED-269]
          example: ED-269

    GeospatialDataSourceResponse:
      type: object
      required:
        - result
      properties:
        result:
          description: >-
            The status of the Geospatial source and the handling of its data by the USS.

            - `Activating`: the USS is processing the request and is currently activating the geospatial data.

            - `Ready`: the geospatial data has been successfully activated and the USS is ready to receive test requests.

            - `Deactivating`: the geospatial dataset is being deactivated.
            
            - `Deactivated`: the geospatial dataset has been deactivated (the USS may instead return 404 as well).

            - `Unsupported`: the USS cannot process the dataset type specified.

            - `Rejected`: the geospatial data source was rejected because it is invalid.

            - `Error`: the geospatial data activation or deactivation failed. The message field is required in this case.
          type: string
          enum: [Activating, Ready, Deactivating, Deactivated, Unsupported, Rejected, Error]
          example: Ready
        message:
          description: Human-readable explanation of the result for debugging purpose only. This field is required when the result value is `Error`.
          type: string
          example: |-
            Unable to download the dataset https://caa.example.com/geozones.json. Connection refused.

    #######################################################################
    #################### Start of ED-269 definitions    ###################
    #######################################################################

    UomDimensions:
      type: string
      enum:
        - M
        - FT

    VerticalReferenceType:
      type: string
      enum:
        - AGL
        - AMSL

    USpaceClass:
      type: string
      maxLength: 100

    Restriction:
      type: string
      enum:
        - PROHIBITED
        - REQ_AUTHORISATION
        - CONDITIONAL
        - NO_RESTRICTION

    #######################################################################
    #################### END of ED-269 definitions    #####################
    #######################################################################

    Position:
      type: object
      required:
        - uomDimensions
        - verticalReferenceType
      properties:
        uomDimensions:
          $ref: '#/components/schemas/UomDimensions'
        verticalReferenceType:
          $ref: '#/components/schemas/VerticalReferenceType'
        height:
          description: >-
            Height above vertical reference datum indicated in `verticalReferenceType`, in units of `uomDimensions`.
          type: number
          default: 0
        longitude:
          description: >-
            Longitude, degrees east of prime meridian.
          type: number
          default: 0
        latitude:
          description: >-
            Latitude, degrees north of the equator.
          type: number
          default: 0

    GeospatialMapQueryRequest:
      type: object
      required:
        - checks
      properties:
        checks:
          type: array
          items:
            $ref: '#/components/schemas/GeospatialMapCheck'

    GeospatialMapCheck:
      type: object
      required:
        - filterSets
      properties:
        filterSets:
          description: >-
            Select geospatial features which match any of the specified filter sets.
          type: array
          items:
            $ref: '#/components/schemas/GeospatialFeatureFilterSet'

    GeospatialFeatureFilterSet:
      description: >-
        Set of filters to select only a subset of geospatial features.  Only geospatial features which are applicable to all specified filters within this filter set should be selected.
      type: object
      properties:
        position:
          description: >-
            If specified, only select geospatial features encompassing this position.
          anyOf:
            - $ref: '#/components/schemas/Position'
        after:
          description: >-
            If specified, only select geospatial features which encompass at least some times at or after this time.
          type: string
          format: date-time
        before:
          description: >-
            If specified, only select geospatial features which encompass at least some times at or before this time.
          type: string
          format: date-time
        ed269:
          $ref: '#/components/schemas/ED269Filters'

    ED269Filters:
      description: >-
        Filter criteria for the selection of Geozones according to ED-269 characteristics.
      type: object
      properties:
        uSpaceClass:
          description: >-
            If specified, only select Geozones which are of the specified `uSpaceClass`.
          anyOf:
            - $ref: '#/components/schemas/USpaceClass'
        acceptableRestrictions:
          description: >-
            If specified and non-empty, only select Geozones which are one of the specified restriction types.
          type: array
          items:
            $ref: '#/components/schemas/Restriction'

    GeospatialMapQueryReply:
      type: object
      properties:
        results:
          description: >-
            Responses to each of the `checks` in the request.  The number of entries in this array should match the number of entries in the `checks` field of the request.
          type: array
          items:
            $ref: '#/components/schemas/GeospatialMapCheckResult'
          default: []

    GeospatialMapCheckResult:
      type: object
      required:
        - featuresSelectionOutcome
      properties:
        featuresSelectionOutcome:
          type: string
          description: >-
            Indication of whether one or more applicable geospatial features were selected according to the selection criteria of the corresponding check.
            
            * Present: One or more applicable geospatial features were selected.
            * Absent: No applicable geospatial features were selected.
            * UnsupportedFilter: Applicable geospatial features could not be selected because one or more filter criteria are not supported by the USS.  If this value is specified, `message` must be populated.
            * Error: An error or condition not enumerated above occurred.  If this value is specified, `message` must be populated.
          enum:
            - Present
            - Absent
            - UnsupportedFilter
            - Error
        message:
          type: string
          description: >-
            A human-readable description of why the unsuccessful `featuresSelectionOutcome` was reported.  Should only be populated when appropriate according to the value of the `featuresSelectionOutcome` field.
          example: >-
            ED-269 comprehension is not supported.

paths:
  /status:
    get:
      operationId: GetStatus
      security:
        - TestAuthority:
            - interuss.geospatial_map.direct_automated_test
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: >-
            The USS automated testing interface is available and its status was retrieved successfully.
        '401':
          description: Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid.
        '403':
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
        '404':
          description: The USS automated testing interface is not available.
      summary: Status of the USS automated testing interface
      description: Get the status of the USS automated testing interface.

  /geospatial_data_sources/{geospatial_data_source_id}:
    parameters:
      - name: geospatial_data_source_id
        in: path
        required: true
        description: A UUID string identifying a geospatial data source.
        schema:
          $ref: '#/components/schemas/UUIDv4Format'

    put:
      security:
        - TestAuthority:
            - interuss.geospatial_map.direct_automated_test
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGeospatialDataSourceRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeospatialDataSourceResponse'
          description: >-
            Request has been correctly handled and the USS has been instructed to import and activate the geospatial data from the source.
        '401':
          description: Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid.
        '403':
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
      operationId: PutGeospatialDataSource
      summary: Import and activate a geospatial data source
      description: Instructs the USS to import and activate the geospatial data from the specified source.

    get:
      security:
        - TestAuthority:
            - interuss.geospatial_map.direct_automated_test
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeospatialDataSourceResponse'
          description: >-
            The geospatial data source is known by the USS and its status was retrieved successfully.
        '401':
          description: Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid.
        '403':
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
        '404':
          description: The geospatial data source has been successfully deactivated or didn't exist.
      operationId: GetGeospatialDataSourceStatus
      summary: Status of a geospatial data source
      description: Get the status of the geospatial data source in the USS.

    delete:
      security:
        - TestAuthority:
            - interuss.geospatial_map.direct_automated_test
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeospatialDataSourceResponse'
          description: >-
            Request has been correctly handled and the geospatial dataset may be deleted by the USS.
            Status of the dataset may be checked using the GET method until it returns a 404.
        '401':
          description: Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid.
        '403':
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
      operationId: DeleteGeospatialDataSource
      summary: Deactivate a geospatial data source
      description: Instructs the USS to deactivate the geospatial data source and its data.

  /map/queries:
    post:
      security:
        - TestAuthority:
            - interuss.geospatial_map.query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeospatialMapQueryRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeospatialMapQueryReply'
          description: >-
            The query was successfully performed.
        '401':
          description: Bearer access token was not provided in Authorization header, token could not be decoded, or token was invalid.
        '403':
          description: The access token was decoded successfully but did not include a scope appropriate to this endpoint.
      operationId: QueryGeospatialMap
      summary: Check for applicable geospatial features
      description: Check if one or multiple geospatial features are applicable at the position of interest for the specified period of time and operational conditions.
