openapi: 3.0.2
info:
  title: Definitions used in flight planning interface specific to U-space flight authorisation.
components:
  schemas:
    FlightAuthorisationData:
      description: |-
        The details of a UAS flight authorization request, as received from the user.
        
        Note that a full description of a flight authorisation must include mandatory information required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664 for an UAS flight authorisation request. Reference: https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021R0664&from=EN#d1e32-178-1
      type: object
      properties:
        uas_serial_number:
          type: string
          description: Unique serial number of the unmanned aircraft or, if the unmanned aircraft is privately built, the unique serial number of the add-on. This is expressed in the ANSI/CTA-2063 Physical Serial Number format. Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 1.
          example: MFR1C123456789ABC
        operation_mode:
          $ref: '#/components/schemas/OperationMode'
        operation_category:
          type: string
          enum:
            - Unknown
            - Open
            - Specific
            - Certified
          description: |-
            Category of UAS operation (‘open’, ‘specific’, ‘certified’) as defined in COMMISSION DELEGATED REGULATION (EU) 2019/945. Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 4.
          example: Open
        uas_class:
          $ref: '#/components/schemas/UASClass'
        identification_technologies:
          type: array
          items:
            type: string
          description: Technology used to identify the UAS. Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 6.
          example: ['ADS-B', 'ASTMNetRID']
        uas_type_certificate:
          description: |-
            Provisional field. Not applicable as of September 2021. Required only if `uas_class` is set to `other` by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 4.
          type: string
          example: ''
        connectivity_methods:
          type: array
          items:
            type: string
          description: Connectivity methods. Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 7.
          example: ['cellular']
        endurance_minutes:
          description: Endurance of the UAS. This is expressed in minutes. Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 8.
          type: number
          format: int32
          example: 20
        emergency_procedure_url:
          type: string
          format: url
          description: The URL at which the applicable emergency procedure in case of a loss of command and control link may be retrieved. Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 9.
          example: https://utm_uss.com/emergency_procedure
        operator_id:
          type: string
          description: |-
            Registration number of the UAS operator.
            The format is defined in EASA Easy Access Rules for Unmanned Aircraft Systems GM1 to AMC1
            Article 14(6) Registration of UAS operators and ‘certified’ UAS.
            Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 10.
          example: FIN87astrdge12k8
        uas_id:
          description: |-
            When applicable, the registration number of the unmanned aircraft.
            This is expressed using the nationality and registration mark of the unmanned aircraft in
            line with ICAO Annex 7.
            Specified by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 10.
          type: string
          example: HB-XXXX
      required:
        - uas_serial_number
        - operation_mode
        - uas_class
        - identification_technologies
        - operator_id
        - operation_category
        - connectivity_methods
        - endurance_minutes
        - emergency_procedure_url

    OperationMode:
      type: string
      enum:
        - Undeclared
        - Vlos
        - Bvlos
      description: Specify if the operation is a `VLOS` or `BVLOS` operation. Required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 2.
      example: Vlos

    UASClass:
      type: string
      enum:
        - Other
        - C0
        - C1
        - C2
        - C3
        - C4
        - C5
        - C6
      description: Specify the class of the UAS to be flown, the specifition matches EASA class identification label categories. UAS aircraft class as defined in COMMISSION DELEGATED REGULATION (EU) 2019/945 (C0 to C4) and COMMISSION DELEGATED REGULATION (EU) 2020/1058 (C5 and C6). This field is required by ANNEX IV of COMMISSION IMPLEMENTING REGULATION (EU) 2021/664, paragraph 4.
      example: C0
